### PR TITLE
Various changes

### PR DESCRIPTION
**Pull request by ColinMaudry**
Look at the commit comments to get a feel of what these changes are.

Then at the code, of course :)

### CODE REVIEW

**Comment by ColinMaudry** [comment]
La prochaine étape : renommer `mavoix` => `dev`.

@SlyMaVoix Une fois que cette PR est mergée dans `mavoix`, je pull le code sur l'instance de production et tu pourras partager le lien de l'application avec le monde entier :)

**Comment by oceanBigOne** [comment]
Everything is good for me. Just, why not leave the file .gitignore in the tmp folder? (This keeps the folder empty in github)

**Comment by ColinMaudry** [comment]
- to stop tracking files in /tmp, I haved added [a new line](https://github.com/MaVoix/MaVoixSupportGenerator/pull/7/commits/cbe8fc83ba4a28d1e22c005b2fe0d1fc5f94f758#diff-a084b794bc0759e7a6b77810e01874f2R3) in the root .gitignore
- any file present in /tmp gets deleted when the application runs. So .gitignore, like README.md before, always gets deleted eventually. Better keeping it empty.

**Comment by anthony-o** [comment]
@ColinMaudry : the purpose of `mavoix` branch was simply to have a **specific** version for mavoix website, so I think we shouldn't rename the branch `dev`.
Nevertheless we could create a new branch `dev` branched from `mavoix` one and remove all what's specific to mavoix website in it in order to have a "generic" support generator.
@oceanBigOne : I agree we should keep a `.gitignore` file in `tmp` folder (with [this content](http://stackoverflow.com/a/11579945/535203) for example), except if the generator's code is patched in order to create that folder if it doesn't exist (and would be even best to make it configurable in the config file).

**Comment by ColinMaudry** [comment]
@anthony-o 

### Regarding hosting a generic support generator in /MaVoix/MaVoixSupportGenerator

Having two different projects in the same repo, one generic and one specific, is confusing in terms of communication. The code in this repo is called MaVoixSupportGenerator, is hosted by MaVoix, is only used by #MAVOIX (as far as I know).

If one of you wants to work on the generic version, I think they should set up a repo with the generic code on their own GitHub account or Git repo. Making generic software is a very good idea, but also a lot of work as you need to create a customization framework and document it. Personally, I want to focus on MaVoix-specific software.

Seeing the difference of pace between the `master` and `mavoix` branch, the MaVoix specific version will quickly take distance with the generic version and will not wait for the generic version to catch up. When the situation is flipped and the generic version catches up and lead the development, then I'll follow it.

### Ignoring /tmp content

In the current situation, any file present in /tmp gets deleted at runtime. This means that you don't want any file tracked by Git in this folder. I consequently suggested the following solution with this PR:

- removing /tmp completely
- setting an ignore rule in the root .gitignore, so that temporary files in /tmp are not tracked by Git
- adding in the setup instructions that before first run, a /tmp directory must be created

Yes, there are other ways to solve this problem, I opted for the one that doesn't require modifying the PHP code.

**Comment by oceanBigOne** [comment]
I think it's not a good idea to create tmp folder with code because need to chmod 777 the root directory.  It's doesn't matter for me, but for understand : @ColinMaudry  why don't keep this folder with only a gitignore file inside ? Is there any problem with it ? (not good practice or something like that ?) 

Concerning the names of branches, I leave you to choose. I have no Github experience to know what is good or not. Simply, I think the generic project will come later. So we could actually start working on the MAVOIX version only (master and dev). But do as you please.

**Comment by ColinMaudry** [comment]
@oceanBigOne 
> why don't keep this folder with only a gitignore file inside ?

Me:
> In the current situation, any file present in /tmp gets deleted at runtime.

Here is what happens with a /tmp with a file in it:

1. Bob deploys the code (`git clone`) on his server to run the app.
2. when he starts it, (or when someone creates the first picture, I'm not sure) the content of the /tmp is removed in order, I guess, to prevent temporary files to pile up. The .gitignore or .gitkeep file in /tmp has consequently been deleted along with the temporary files.
3. @oceanBigOne pushes new code in Github with new features.
4. Bob wants the new features, so he `git pull` his branch to pull the new code.
5. Git tells him : sorry Bob, you have made a local change (deleted a file tracked by Git) and you cannot pull code if your changes are not commited.
6. Bob consequently must recreate the deleted file in /tmp so that he can pull the new code from the central repo. Bob wishes he could pull code without recreating a file that he doesn't need to run the app.

**Comment by oceanBigOne** [comment]
Ok, thank for the explanation ! I note this for the next version (do not delete the .gitignore file from the tmp folder)

**Comment by ColinMaudry** [comment]
If you want to keep the .gitignore and the /tmp folder, you can edit [the PHP code](https://github.com/MaVoix/MaVoixSupportGenerator/blob/mavoix/index.php#L69) so that the .gitignore file is preserved when the /tmp directory is cleaned.

**Comment by anthony-o** [comment]
There is an other solution: create an empty file (for example [`.gitkeep`](http://stackoverflow.com/q/7229885/535203)) inside `/tmp` folder and declare `/tmp/*` (and perhaps also `/tmp/.*`?) inside the root `/.gitignore`.

In that case, I think git will ignore every modification inside the `tmp` directory, even the deletion of the `.gitkeep` file (which is required only because in Git you can't commit empty dirs).

**Comment by ColinMaudry** [comment]
Just to be clear: you are both proposing solutions (editing PHP code | adding a .gitkeep file) so that the user doesn't have to create a /tmp folder, **one time**, when they clone the code?

Or there is another reason?

If that's the reason, I believe these solutions require quite some engineering for such a trivial issue.

**Comment by oceanBigOne** [comment]
To be clear in my turn :)

I was not aware that my script will delete the .gitignore file at the same time as the other files. So I will update the script to no longer deletes this file soon as possible. But for now, I think @ColinMaudry's solution is good.

**Comment by oceanBigOne** [comment]
( .gitignore and .gitkeep)

**Comment by ColinMaudry** [comment]
Thanks.

@SlyMaVoix wanted to share the link of the app today on social networks.

I consequently think that for now we go with my PR as-is and I deploy it on https://jemaffiche.mavoix.info. 

If you really are not happy with not having a /tmp folder at clone time, code your alternate solution, make a PR, and give arguments in favor of your alternate solution.

@anthony-o Is this way of proceeding okay for you?

**Comment by ColinMaudry** [comment]
@anthony-o We had a deadline to propose a stable acceptable for this evening so that @SlyMaVoix can communicate about the app.

I merge, but as previously stated, argumented PRs are most welcome.

**Pull request merged**
